import type { DemoPreset } from "./types";

// gym poster demo preset
export const gymPoster: DemoPreset = {
  id: "gym_poster" as any,
  name: "Gym / Fitness Poster",
  description: "Create a bold, modern gym or fitness promotional poster",
  prompt: "Create a gym membership poster with pricing and schedule",
  language: "english",
  locationType: "hall" as any,

  analyzePhrases: [
    { text: "Understanding your request...", durationMs: 700 },
    { text: "Detecting poster type — Gym / Fitness", durationMs: 1100 },
    { text: "Selecting high-energy design style...", durationMs: 900 },
    { text: "Preparing customization options...", durationMs: 600 },
  ],

  collectConfig: {
    title: "Gym Poster Details",
    description: "Enter your gym info and we'll craft a bold poster for you",
    groups: [
      { id: "gym", label: "Gym Info", icon: "dumbbell" },
      { id: "pricing", label: "Pricing & Offer", icon: "badge-percent" },
      { id: "schedule", label: "Schedule & Contact", icon: "clock" },
      { id: "style", label: "Style", icon: "palette" },
    ],
    fields: [
      {
        id: "gym_name",
        type: "text",
        label: "Gym / Studio Name",
        placeholder: "e.g. Iron Temple Fitness",
        required: true,
        group: "gym",
      },
      {
        id: "tagline",
        type: "text",
        label: "Tagline / Slogan",
        placeholder: "e.g. Transform Your Body, Transform Your Life",
        group: "gym",
      },
      {
        id: "offer_headline",
        type: "text",
        label: "Offer Headline",
        placeholder: "e.g. NEW YEAR SPECIAL",
        group: "pricing",
      },
      {
        id: "monthly_price",
        type: "text",
        label: "Monthly Price",
        placeholder: "e.g. ₹999/mo",
        group: "pricing",
      },
      {
        id: "annual_price",
        type: "text",
        label: "Annual Price",
        placeholder: "e.g. ₹8,999/yr",
        group: "pricing",
      },
      {
        id: "discount_note",
        type: "text",
        label: "Discount / Promo Note",
        placeholder: "e.g. First month FREE, 20% off for students",
        group: "pricing",
      },
      {
        id: "timings",
        type: "text",
        label: "Operating Hours",
        placeholder: "e.g. 5 AM – 11 PM, Mon – Sat",
        group: "schedule",
      },
      {
        id: "phone",
        type: "text",
        label: "Contact Number",
        placeholder: "e.g. +91 98765 43210",
        group: "schedule",
      },
      {
        id: "address",
        type: "text",
        label: "Address",
        placeholder: "e.g. 2nd Floor, MG Road, Pune",
        group: "schedule",
      },
      {
        id: "facilities",
        type: "select",
        label: "Key Facilities (pick main ones)",
        defaultValue: "weights",
        options: [
          { value: "weights", label: "Weight Training" },
          { value: "cardio", label: "Cardio Zone" },
          { value: "crossfit", label: "CrossFit" },
          { value: "yoga", label: "Yoga Studio" },
          { value: "zumba", label: "Zumba / Dance" },
          { value: "personal", label: "Personal Training" },
        ],
        group: "gym",
      },
      {
        id: "theme",
        type: "select",
        label: "Design Theme",
        defaultValue: "dark_energy",
        options: [
          { value: "dark_energy", label: "Dark & Energetic" },
          { value: "neon", label: "Neon Glow" },
          { value: "clean_bold", label: "Clean & Bold" },
          { value: "urban", label: "Urban / Street" },
        ],
        group: "style",
      },
      {
        id: "include_person",
        type: "toggle",
        label: "Include fitness person image",
        defaultValue: true,
        group: "style",
      },
    ],
  },

  canvasWidth: 800,
  canvasHeight: 1100,

  background: {
    type: "gradient",
    colors: ["#0D0D0D", "#1A1A2E"],
    direction: "vertical",
  },

  textElements: [
    {
      id: "gym_logo_text",
      text: "{{gym_name}}",
      fontSize: 56,
      fontFamily: "Oswald",
      fontWeight: 800,
      fill: "#FFFFFF",
      position: { x: 400, y: 100 },
      textAlign: "center",
      charSpacing: 80,
    },
    {
      id: "gym_tagline",
      text: "{{tagline}}",
      fontSize: 18,
      fontFamily: "Inter",
      fill: "#A0AEC0",
      position: { x: 400, y: 165 },
      textAlign: "center",
      opacity: 0.85,
    },
    {
      id: "gym_offer_headline",
      text: "{{offer_headline}}",
      fontSize: 42,
      fontFamily: "Oswald",
      fontWeight: 700,
      fill: "#F6E05E",
      position: { x: 400, y: 400 },
      textAlign: "center",
      charSpacing: 60,
    },
    {
      id: "gym_price_monthly",
      text: "{{monthly_price}}",
      fontSize: 64,
      fontFamily: "Oswald",
      fontWeight: 800,
      fill: "#48BB78",
      position: { x: 280, y: 500 },
      textAlign: "center",
    },
    {
      id: "gym_price_annual",
      text: "{{annual_price}}",
      fontSize: 40,
      fontFamily: "Oswald",
      fontWeight: 700,
      fill: "#68D391",
      position: { x: 550, y: 510 },
      textAlign: "center",
      opacity: 0.9,
    },
    {
      id: "gym_discount",
      text: "{{discount_note}}",
      fontSize: 20,
      fontFamily: "Inter",
      fontWeight: 600,
      fill: "#FC8181",
      position: { x: 400, y: 590 },
      textAlign: "center",
    },
    {
      id: "gym_timings",
      text: "{{timings}}",
      fontSize: 18,
      fontFamily: "Inter",
      fill: "#CBD5E0",
      position: { x: 400, y: 700 },
      textAlign: "center",
    },
    {
      id: "gym_phone",
      text: "{{phone}}",
      fontSize: 22,
      fontFamily: "Inter",
      fontWeight: 600,
      fill: "#FFFFFF",
      position: { x: 400, y: 750 },
      textAlign: "center",
    },
    {
      id: "gym_address",
      text: "{{address}}",
      fontSize: 16,
      fontFamily: "Inter",
      fill: "#A0AEC0",
      position: { x: 400, y: 790 },
      textAlign: "center",
      width: 500,
      opacity: 0.8,
    },
    {
      id: "gym_cta",
      text: "JOIN NOW",
      fontSize: 32,
      fontFamily: "Oswald",
      fontWeight: 700,
      fill: "#0D0D0D",
      position: { x: 400, y: 880 },
      textAlign: "center",
    },
  ],

  imageElements: [
    {
      id: "gym_img_hero",
      query: "fitness gym person workout dark",
      position: { x: 400, y: 280 },
      width: 350,
      opacity: 0.6,
    },
    {
      id: "gym_img_accent",
      query: "gym dumbbell icon flat",
      position: { x: 80, y: 880 },
      width: 60,
      opacity: 0.5,
    },
    {
      id: "gym_img_accent2",
      query: "fitness kettlebell icon",
      position: { x: 720, y: 880 },
      width: 60,
      opacity: 0.5,
    },
  ],

  steps: [
    {
      id: "gym_step_bg",
      type: "set_background",
      label: "Setting dark background",
      description: "Applying high-contrast dark gradient",
      toolName: "apply_gradient_background",
      toolArgs: {
        colors: ["#0D0D0D", "#1A1A2E"],
        direction: "vertical",
      },
      thinkingDurationMs: 500,
      executionDurationMs: 350,
    },
    {
      id: "gym_step_font",
      type: "apply_font",
      label: "Loading Oswald typeface",
      description: "Preparing bold display font",
      toolName: "load_font",
      toolArgs: { fontFamily: "Oswald" },
      thinkingDurationMs: 400,
      executionDurationMs: 700,
    },
    {
      id: "gym_step_name",
      type: "add_text",
      label: "Adding gym name",
      description: "Placing main heading",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_logo_text" },
      thinkingDurationMs: 500,
      executionDurationMs: 300,
      dependsOn: "gym_step_font",
    },
    {
      id: "gym_step_tagline",
      type: "add_text",
      label: "Adding tagline",
      description: "Placing slogan text",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_tagline" },
      thinkingDurationMs: 350,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_hero_img",
      type: "add_image",
      label: "Searching hero image",
      description: "Finding fitness hero background image",
      toolName: "search_images",
      toolArgs: { imageRef: "gym_img_hero" },
      thinkingDurationMs: 700,
      executionDurationMs: 1200,
    },
    {
      id: "gym_step_offer",
      type: "add_text",
      label: "Adding offer headline",
      description: "Placing promotional headline",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_offer_headline" },
      thinkingDurationMs: 400,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_price_monthly",
      type: "add_text",
      label: "Adding monthly price",
      description: "Placing pricing info",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_price_monthly" },
      thinkingDurationMs: 350,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_price_annual",
      type: "add_text",
      label: "Adding annual price",
      description: "Placing yearly pricing",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_price_annual" },
      thinkingDurationMs: 300,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_discount",
      type: "add_text",
      label: "Adding discount note",
      description: "Highlighting promo details",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_discount" },
      thinkingDurationMs: 350,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_timings",
      type: "add_text",
      label: "Adding operating hours",
      description: "Placing schedule info",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_timings" },
      thinkingDurationMs: 300,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_phone",
      type: "add_text",
      label: "Adding contact number",
      description: "Placing phone details",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_phone" },
      thinkingDurationMs: 250,
      executionDurationMs: 200,
    },
    {
      id: "gym_step_address",
      type: "add_text",
      label: "Adding address",
      description: "Placing location info",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_address" },
      thinkingDurationMs: 300,
      executionDurationMs: 250,
    },
    {
      id: "gym_step_cta_bg",
      type: "set_background",
      label: "Creating CTA button",
      description: "Adding call-to-action background shape",
      toolName: "spawn_shape",
      toolArgs: {
        shapeType: "rectangle",
        options: {
          fill: "#F6E05E",
          width: 250,
          height: 55,
          position: { x: 275, y: 865 },
          rx: 6,
          ry: 6,
        },
      },
      thinkingDurationMs: 400,
      executionDurationMs: 300,
    },
    {
      id: "gym_step_cta_text",
      type: "add_text",
      label: "Adding CTA text",
      description: "Placing JOIN NOW button text",
      toolName: "add_text",
      toolArgs: { elementRef: "gym_cta" },
      thinkingDurationMs: 300,
      executionDurationMs: 250,
      dependsOn: "gym_step_cta_bg",
    },
    {
      id: "gym_step_accent1",
      type: "add_image",
      label: "Adding accent icon",
      description: "Searching for dumbbell decoration",
      toolName: "search_images",
      toolArgs: { imageRef: "gym_img_accent" },
      thinkingDurationMs: 500,
      executionDurationMs: 800,
    },
    {
      id: "gym_step_accent2",
      type: "add_image",
      label: "Adding accent icon",
      description: "Searching for kettlebell decoration",
      toolName: "search_images",
      toolArgs: { imageRef: "gym_img_accent2" },
      thinkingDurationMs: 400,
      executionDurationMs: 800,
    },
    {
      id: "gym_step_finalize",
      type: "finalize",
      label: "Finalizing poster",
      description: "Adjusting layout and element spacing",
      toolName: "finalize_layout",
      toolArgs: {},
      thinkingDurationMs: 500,
      executionDurationMs: 400,
    },
  ],
};

// theme color maps for gym posters
export const GYM_THEMES: Record<
  string,
  {
    bg: string[];
    primary: string;
    accent: string;
    cta: string;
    text: string;
    muted: string;
  }
> = {
  dark_energy: {
    bg: ["#0D0D0D", "#1A1A2E"],
    primary: "#FFFFFF",
    accent: "#F6E05E",
    cta: "#F6E05E",
    text: "#CBD5E0",
    muted: "#A0AEC0",
  },
  neon: {
    bg: ["#0A0A0A", "#1A0A2E"],
    primary: "#FFFFFF",
    accent: "#00FF87",
    cta: "#00FF87",
    text: "#C4F1D9",
    muted: "#76E4A7",
  },
  clean_bold: {
    bg: ["#F7FAFC", "#EDF2F7"],
    primary: "#1A202C",
    accent: "#E53E3E",
    cta: "#E53E3E",
    text: "#4A5568",
    muted: "#A0AEC0",
  },
  urban: {
    bg: ["#1A1A1A", "#2D2D2D"],
    primary: "#FFFFFF",
    accent: "#ED8936",
    cta: "#ED8936",
    text: "#E2E8F0",
    muted: "#A0AEC0",
  },
};

// resolves template placeholders with collected data
export function resolveGymText(
  template: string,
  data: Record<string, unknown>,
): string {
  let resolved = template;

  Object.entries(data).forEach(([key, value]) => {
    if (typeof value === "string" && value.trim()) {
      resolved = resolved.replace(
        new RegExp(`\\{\\{${key}\\}\\}`, "g"),
        value,
      );
    }
  });

  // remove unfilled placeholders
  resolved = resolved.replace(/\{\{[^}]+\}\}/g, "").trim();

  return resolved;
}
